PYTHON_DIST_DIR=dist

python/dist: pipenv setup.py pipenv/generate_requirements
	$(WITH_PIPENV) python setup.py sdist
.PHONY: python/dist

python/distif:
	test -f $(PYTHON_DIST_DIR)/*.tar.gz || $(MAKE) python/dist
.PHONY: python/distif
